"use client";

import { useState } from "react";
import { Card, Badge } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import { plannerTasks } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

const TABS = [
  { key: "daily", label: "Daily" },
  { key: "weekly", label: "Weekly" },
  { key: "monthly", label: "Monthly" },
] as const;

type TabKey = (typeof TABS)[number]["key"];

export default function PlannerPage() {
  const [tab, setTab] = useState<TabKey>("daily");
  const [adjustOpen, setAdjustOpen] = useState(false);
  const [tasks, setTasks] = useState(plannerTasks);

  function toggleTask(id: number) {
    setTasks((prev) => ({
      ...prev,
      [tab]: prev[tab].map((t) => (t.id === id ? { ...t, done: !t.done } : t)),
    }));
  }

  const list = tasks[tab];

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold text-on-surface">Study Planner</h1>
          <p className="text-xs text-on-surface-variant mt-1 flex items-center gap-1.5">
            <Icon name="auto_awesome" className="text-[16px] text-primary" />
            Generated by AI based on your progress
          </p>
        </div>
        <Button variant="outline" onClick={() => setAdjustOpen(true)}>
          <Icon name="tune" className="text-[18px]" />
          Adjust Plan
        </Button>
      </div>

      <div className="inline-flex rounded-full border border-outline-variant p-1 bg-surface-container-low">
        {TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={cn(
              "px-4 py-1.5 rounded-full text-sm font-medium transition-colors",
              tab === t.key ? "bg-primary text-on-primary" : "text-on-surface-variant"
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      <Card className="divide-y divide-outline-variant/30">
        {list.map((task) => (
          <div key={task.id} className="flex items-center gap-3 px-5 py-4">
            <button onClick={() => toggleTask(task.id)}>
              <Icon
                name={task.done ? "check_circle" : "radio_button_unchecked"}
                filled={task.done}
                className={task.done ? "text-primary" : "text-on-surface-variant"}
              />
            </button>
            <div className="flex-1 min-w-0">
              <p className={cn("text-sm font-medium", task.done ? "line-through text-on-surface-variant" : "text-on-surface")}>
                {task.label}
              </p>
              <div className="flex items-center gap-2 mt-1">
                <Badge tone="secondary">{task.subject}</Badge>
                <span className="text-xs text-on-surface-variant flex items-center gap-1">
                  <Icon name="schedule" className="text-[14px]" />
                  {task.time}
                </span>
              </div>
            </div>
          </div>
        ))}
      </Card>

      {adjustOpen && (
        <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center">
          <div className="absolute inset-0 bg-black/40" onClick={() => setAdjustOpen(false)} />
          <div className="relative w-full md:max-w-md bg-surface-container-lowest rounded-t-2xl md:rounded-2xl p-6 shadow-2xl">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-semibold text-on-surface">Adjust Plan</h2>
              <button onClick={() => setAdjustOpen(false)} className="h-8 w-8 flex items-center justify-center rounded-full hover:bg-surface-container">
                <Icon name="close" />
              </button>
            </div>
            <p className="text-sm text-on-surface-variant">
              Manually editing tasks will be available once the planner is connected to your live study data (Phase 3 — AI Integration).
            </p>
            <Button className="w-full mt-6" onClick={() => setAdjustOpen(false)}>
              Got it
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}